version: "3.9"

services: 
  redis_db:
    image: redis/redis-stack
    ports: 
    - "8001:8001"
    - "6379:6379"
    
  web_api:
    image: madmagic/redisapi
    restart: always
    ports:
    - "5000:80"
    - "5001:5000"
    depends_on:
      - redis_db



