version: "3.9"

services: 
  redis_db:
    image: redis/redis-stack
    ports: 
    - "8001:8001"
    - "6379:6379"
    volumes:
      - ./redis_data:/data/
      - ./redis-dumb:/var/lib/redis/
      - ./redis-stack.conf:/redis-stack.conf
    
  madmagic:
    image: madmagic
    build:
      context: .
      dockerfile: MvcMadMagic/Dockerfile
    ports:
        - "8080:80"
        - "8081:443"
    depends_on:
      - redisapi

  redisapi:
    image: redisapi
    build:
      context: .
      dockerfile: RedisApi/Dockerfile
    ports:
        - "5000:80"
        - "5001:5000"
    depends_on:
      - redis_db

  
